services:
  keycloak:
    container_name: keycloak  # This ensures docker exec keycloak works
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data

  todo-service:
    container_name: todo-service
    build: .
    ports:
      - "3000:3000"
    environment:
      RUST_LOG: debug
    depends_on:
      - keycloak

volumes:
  keycloak_data: